#ifndef MACROS_H
#define MACROS_H

#define INODE_MAP 1
#define FREE_BLOCK_MAP 2

#define BLOCK_SIZE 4096
#define NUM_BLOCK 1024

#define SPEC_SIZE 7

#define INODE_SIZE 64
#define INODE_FIRST_BLOCK 3

#define INODES_PER_BLOCK (BLOCK_SIZE / INODE_SIZE)

#define DIRECTORY_SIZE 32

#endif